export {default as Inicio} from './home'
export {default as Categorias} from './categorias'
export {default as Productos} from './productos'
export {default as DetalleProducto} from './detalleproducto'
export {default as CartScreen} from './cart'
export {default as OrdersScreen} from './orders'